apiVersion: apps/v1
kind: Deployment
metadata:
  name: steward
spec:
  template:
    spec:
      containers:
      - name: steward
        image: ghcr.io/profianinc/steward:v0.2.0-rc2
        imagePullPolicy: Always
