apiVersion: apps/v1
kind: Deployment
metadata:
  name: drawbridge
spec:
  replicas: 3
  template:
    spec:
      containers:
      - image: ghcr.io/profianinc/drawbridge:0.4.0
        name: drawbridge
