apiVersion: apps/v1
kind: Deployment
metadata:
  name: steward
spec:
  replicas: 1
  foo
  template:
    spec:
      containers:
      - name: steward
        image: ghcr.io/profianinc/steward:test
        # main is a rolling branch, make sure to always re-pull
        imagePullPolicy: Always
