apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps-testing
  namespace: flux-system
spec:
  interval: 1m
  dependsOn:
  - name: infrastructure
  sourceRef:
    kind: GitRepository
    name: k8s-config
  path: ./apps/testing
  force: true
  prune: true
  wait: true
  timeout: 10m
